version: '2.2'

services:
  web1:
    build: .
    restart: always
    volumes:
      - static_volume:/app/static:rw
      - sqlite_data:/app/data
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=mysite.settings
  # Django应用2（用于负载均衡）
  web2:
    build: .
    restart: always
    volumes:
      - static_volume:/app/static:rw
      - sqlite_data:/app/data
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=mysite.settings

  # Nginx服务（负载均衡+动静分离）
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/django_nginx.conf
      - static_volume:/app/static
    depends_on:
      - web1
      - web2
volumes:
  static_volume:
  sqlite_data:
